import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";
import { DescriptionProvider } from "./components/DescriptionProvider";
import PersistentBody from "./components/PersistentBody";
import Headd from "./components/Headd";
import Socials from "./components/Socials";
import Footer from "./components/Footer";
import GsapInitializer from "./components/GsapInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const theme = localStorage.getItem('theme');
                if (theme === 'dark') {
                  document.documentElement.classList.add('dark');
                }
              })()
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
        style={{ backgroundColor: 'var(--foreground)' }}
      >
        <GsapInitializer />
        <ThemeProvider>
          <DescriptionProvider>
            {/* Rounded border frame */}
            <div className="fixed inset-2 border-2 rounded-2xl pointer-events-none z-[9999]" style={{ borderColor: 'var(--background)' }}></div>

            {/* Website content inside the border */}
            <div className="fixed inset-2 rounded-2xl overflow-hidden z-10" style={{ backgroundColor: 'var(--background)' }}>
              <div id="main-scroll-container" className="h-full w-full overflow-y-auto overflow-x-hidden">
                <Headd />
                <PersistentBody />
                {children}
                {/* <Socials /> */}
                <Footer />
              </div>
            </div>
          </DescriptionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
